/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // Dynamic classes for QuickActions component
    'hover:border-blue-300',
    'hover:border-green-300',
    'hover:border-purple-300',
    'hover:border-orange-300',
    'hover:border-red-300',
    'hover:border-indigo-300',
    'hover:bg-blue-50',
    'hover:bg-green-50',
    'hover:bg-purple-50',
    'hover:bg-orange-50',
    'hover:bg-red-50',
    'hover:bg-indigo-50',
    'bg-blue-100',
    'bg-green-100',
    'bg-purple-100',
    'bg-orange-100',
    'bg-red-100',
    'bg-indigo-100',
    'text-blue-600',
    'text-green-600',
    'text-purple-600',
    'text-orange-600',
    'text-red-600',
    'text-indigo-600',
    'group-hover:bg-blue-200',
    'group-hover:bg-green-200',
    'group-hover:bg-purple-200',
    'group-hover:bg-orange-200',
    'group-hover:bg-red-200',
    'group-hover:bg-indigo-200',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
